### ISSUE TITLE
Accept stream in

### ISSUE THREAD

**Issue by geekgonecrazy** [antelle/node-stream-zip#1]
We've got zip files stored in GridFS would be nice to be able to pass the stream into this.

**Comment by antelle** [comment]
Good proposal, but to implement it in proper way (without reading the whole file into memory), the stream must support random access mode (zip files are read from end). That's why files are opened as fd and not as streams.
Is there any way to seek within an open file in GridFS?

**Comment by antelle** [comment]
seems there's no way to set position

**Comment by geekgonecrazy** [comment]
Fair enough.  Thanks for taking a look

**Comment by dodekeract** [comment]
There is a way. But it only comes into effect after the document size limit was exceeded. This would basically mean that this module has to read about 16 MiB chunks AFAIK, but it's possible to read the chunk you want to read separately.

**Comment by klesun** [comment]
Would not it still make sense to add an option to accept `fd` and `fileSize` as a parameter instead of file name? `GridFS` is not the only way user of the lib may get a random access stream of a zip file that is not located in his disk. In my case stream is from [torrent-stream](https://github.com/mafintosh/torrent-stream) for example.

**Comment by antelle** [comment]
@klesun makes sense, added it, enjoy

**Comment by klesun** [comment]
lol, thank you very much!
