### ISSUE TITLE
Bad archive error on seemingly fine archive

### ISSUE THREAD

**Issue by arthuro555** [antelle/node-stream-zip#70]
I have a weird error where it calls an archive bad archive, where it opens fine in 7zip. Though, the archive does seem to have a problem as if I zip it with 7zip, it works again. I can't rely on 7zip being installed to unzip in my script though. Here is a video of the issue:

https://user-images.githubusercontent.com/19349038/103459166-65a29700-4d0d-11eb-9d02-06ca5912a1cc.mp4

You can find the zip I tried to open [here](https://github.com/4ian/GDevelop/releases/download/v5.0.0-beta102/GDevelop-5-5.0.0-beta102-mac.zip).

**Comment by antelle** [comment]
Hi! Please paste a piece of code you used to read this archive.

**Comment by arthuro555** [comment]
The video shows the code used. I am just initializing a StreamZip instance with the file path and `storeEntries` set to true.

**Comment by antelle** [comment]
If it was a paid product, I would ask customer support to extract this from your video. I don't have neither time, nor wish to do that myself, sorry.

**Comment by arthuro555** [comment]
The code in the editor is irrelevant, the one-liner in the node repl (in the terminal) showcases the problem. I am sorry for the confusion.

**Comment by antelle** [comment]
I see, I thought it was somehow related to the way the library is used, let me try opening your archive then...

**Comment by antelle** [comment]
Interesting, `7z` gives a warning about it:
```
7z t ~/Downloads/GDevelop-5-5.0.0-beta102-mac.zip

...
             
WARNINGS:
There are data after the end of archive
```

**Comment by antelle** [comment]
Just checked, [adm-zip](https://github.com/cthackers/adm-zip) gives a similar error on this archive as well:
```
Error: Invalid or unsupported zip format. No END header found
```

Same about `unzip`:
```
unzip GDevelop-5-5.0.0-beta102-mac.zip
Archive:  GDevelop-5-5.0.0-beta102-mac.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of GDevelop-5-5.0.0-beta102-mac.zip or
        GDevelop-5-5.0.0-beta102-mac.zip.zip, and cannot find GDevelop-5-5.0.0-beta102-mac.zip.ZIP, period.
```

So, we won't fix it here, since the archive is broken and opening broken zip archives is out of scope of this library. What you can do, if you opening archives like this is necessary in your case, is the following:

1. find a library that allows opening such archives
2. find a library that does archive analysis and remove extra bytes from the file
3. use `7z` to extract files from such archives
4. modify the library so that it scans the archive instead of reading the central directory first, this is most likely practically impossible

**Comment by arthuro555** [comment]
Thank you for investigating my problem and for this precise answer. I will try to find another solution.

**Comment by antelle** [comment]
You're welcome! About 7zip, I remember I used [node-7z](https://github.com/quentinrossetti/node-7z) in the past, it's just a wrapper around the `7z` tool, maybe you will find it useful because 7z seems to be able to open it.
